# Branded Fallback Configuration
# Phase 7.3: Used when Foundation/SR entries don't exist for salad components
#
# Applied only when _align_single_component finds no Foundation/SR match
# Helps components like croutons and dressings align to generic branded entries

version: 1

fallbacks:
  # Lettuce
  lettuce romaine raw:
    - "Lettuce, romaine, raw"
    - "Romaine lettuce"
    - "Lettuce romaine"

  lettuce mixed greens:
    - "Lettuce, green leaf, raw"
    - "Lettuce, red leaf, raw"
    - "Mixed greens"

  # Cheese
  parmesan cheese grated:
    - "Cheese, parmesan, grated"
    - "Parmesan cheese"
    - "Grated parmesan"

  # Croutons
  croutons:
    - "Croutons, plain"
    - "Croutons, seasoned"
    - "Croutons"

  # Dressings
  caesar dressing:
    - "Salad dressing, caesar"
    - "Salad dressing, caesar, regular"
    - "Caesar dressing"

  # Vegetables
  tomatoes raw:
    - "Tomatoes, raw"
    - "Tomato, raw"

  cucumber with peel raw:
    - "Cucumber, with peel, raw"
    - "Cucumber, raw"
