apple:
- strudel
- pie
- juice
- sauce
- chip
- dried
grape:
- juice
- jam
- jelly
- raisin
almond:
- oil
- butter
- flour
- meal
- paste
cucumber:
- sea cucumber
- yane
- alaska native
- pickled
olive:
- oil
- extra virgin
- light tasting
- salad or cooking
- loaf
- spread
potato:
- bread
- flour
- starch
- powder
sweet_potato:
- leave
- leaf
- flour
- starch
- powder
carrot:
- juice
- puree
- baby-food
- canned
pineapple:
- canned
- syrup
blueberry:
- muffin
strawberry:
- topping
salad:
- dressing
celery:
- cream of
- soup
- condensed
- tomato products
- sauce with onions
spinach:
- baby food
- babyfood
- puree
- creamed
- strained
tomato:
- soup
- condensed
egg:
- bread egg
- toast
- sandwich
- roll
- bun
avocado:
- oil
- spread
broccoli:
- soup
- cheese
produce_hard_blocks:
- babyfood
- pickled
- canned
- frozen
- juice
- dried
- dehydrated
- syrup
- in syrup
- in juice
- sweetened
- oil
- stuffed
- pimiento
- cured
- brined
- soup
- cheese
- sea cucumber
eggs_hard_blocks:
- yolk raw frozen
- white raw frozen
- mixture
- pasteurized
- frozen
- substitute
- powder
- powdered
- bread
- toast
- roll
- bun
stage1c_processed_penalties:
- frozen
- pickled
- canned
- brined
- cured
- stuffed
- powder
- powdered
- dehydrated
- dried
- in syrup
- in juice
- oil
- sauce
- soup
- cheese
stage1c_raw_synonyms:
- raw
- fresh
- uncooked
- unprocessed
tatsoi:
- all
deprecated:
- all
white_wine:
- all
red_wine:
- all
beer:
- all
wine:
- all
vodka:
- all
whiskey:
- all
rum:
- all
tequila:
- all
sake:
- all
