# Negative vocabulary for hard filtering BEFORE scoring
#
# Filters are applied to raw FDC entry names (case-insensitive substring match)
# If any negative term found in entry name, candidate is skipped entirely

apple:
  - strudel
  - pie
  - juice
  - sauce
  - chip
  - dried

grape:
  - juice
  - jam
  - jelly
  - raisin

almond:
  - oil
  - butter
  - flour
  - meal
  - paste

# Cucumber safeguard: prevent matching "Sea cucumber yane (Alaska Native)"
cucumber:
  - sea cucumber
  - yane
  - alaska native
  - pickled  # Phase 7.1: unless method indicates pickled

# Olive safeguard: prevent matching "Oil olive salad or cooking"
olive:
  - oil
  - extra virgin
  - light tasting
  - salad or cooking
  - loaf  # Phase 7.1: prevent "Olive loaf pork"
  - spread  # Phase 7.1

potato:
  - bread
  - flour
  - starch
  - powder

sweet_potato:
  - leave
  - leaf
  - flour
  - starch
  - powder

# Carrot safeguard: prevent matching juice/puree when form=raw
carrot:
  - juice
  - puree
  - baby-food
  - canned

# Pineapple safeguard: prefer fresh/raw over canned/syrup for raw forms
pineapple:
  - canned
  - syrup

# Blueberry safeguard: prevent matching muffins/baked goods
blueberry:
  - muffin

# Strawberry safeguard: prevent matching toppings/syrups
strawberry:
  - topping

# Salad safeguard: prefer leafy greens over dressings
salad:
  - dressing

# Phase 7.1: Additional safeguards from 370-image batch analysis

# Celery safeguard: prevent matching soups
celery:
  - cream of
  - soup
  - condensed

# Spinach safeguard: prevent matching baby food
spinach:
  - baby food
  - babyfood
  - puree
  - creamed
  - strained

# Tomato safeguard: prevent matching soups
tomato:
  - soup
  - condensed

# Eggs safeguard: prevent matching bread/composite products
egg:
  - bread egg
  - toast
  - sandwich

# Avocado safeguard: prevent matching oil
avocado:
  - oil
  - spread
