# Food variant mappings for canonical query generation
#
# Helps search_normalizer expand query variants to improve FDC matching
# Plural-first ordering still applies in the normalizer

egg:
  - egg whole
  - egg scrambled
  - egg fried
  - egg omelet

egg_white:
  - egg white
  - egg white cooked
  - egg white scrambled

corn:
  - corn
  - corn kernels
  - sweet corn
  - corn sweet yellow raw
  - corn on the cob

carrot:
  - carrot
  - carrots

cucumber:
  - cucumber
  - cucumbers
  - cucumber peeled  # Phase 7.1

olive:
  - olive
  - olives
  - kalamata olive
  - green olive
  - olives ripe  # Phase 7.1
  - olives green  # Phase 7.1
  - olives black  # Phase 7.1
  - table olives  # Phase 7.1

# Phase 7.1: Additional variants from 370-image batch analysis

celery:
  - celery
  - celery stalk
  - celery sticks

spinach:
  - spinach
  - spinach leaves
  - baby spinach

tomato:
  - tomato
  - tomatoes
  - tomato vine-ripe

avocado:
  - avocado
  - avocados

salad:
  - romaine lettuce
  - mixed greens
  - salad mix
  - leafy greens

pizza:
  - pizza
  - cheese pizza
  - pizza slice

bagel:
  - bagel
  - bagels

meatball:
  - meatball
  - meatballs

dumpling:
  - dumpling
  - dumplings

chicken_salad:
  - chicken salad

caesar_salad:
  - caesar salad
  - romaine

cheese:
  - cheese
  - shredded cheese
