# Food variant mappings for canonical query generation
#
# Helps search_normalizer expand query variants to improve FDC matching
# Plural-first ordering still applies in the normalizer

egg:
  - egg whole
  - egg scrambled
  - egg fried
  - egg omelet

egg_white:
  - egg white
  - egg white cooked
  - egg white scrambled

corn:
  - corn
  - corn kernels
  - sweet corn
  - corn sweet yellow raw
  - corn on the cob

carrot:
  - carrot
  - carrots

cucumber:
  - cucumber
  - cucumbers
  - cucumber peeled  # Phase 7.1

olive:
  - olive
  - olives
  - kalamata olive
  - green olive
  - olives ripe  # Phase 7.1
  - olives green  # Phase 7.1
  - olives black  # Phase 7.1
  - table olives  # Phase 7.1

# Phase 7.1: Additional variants from 370-image batch analysis

celery:
  - celery
  - celery stalk
  - celery sticks

spinach:
  - spinach
  - spinach leaves
  - baby spinach
  - spinach raw

tomato:
  - tomato
  - tomatoes
  - tomato vine-ripe

avocado:
  - avocado
  - avocados

# Phase 7.3: Enhanced salad/greens variants for decomposition

romaine_lettuce:
  - romaine
  - lettuce romaine
  - romaine lettuce
  - lettuce romaine raw  # Phase 7.3 component matching

mixed_greens:
  - mixed greens
  - lettuce mixed greens
  - spring mix
  - mesclun

salad:
  - salad
  - house salad
  - garden salad
  - caesar salad
  - caesar
  - chef salad
  - side salad
  - romaine salad
  - mixed green salad
  - green salad
  - romaine lettuce
  - salad mix
  - leafy greens

# Phase 7.3: Salad component variants
lettuce_romaine_raw:
  - Lettuce, romaine, raw
  - lettuce romaine raw
  - romaine raw
  - lettuce romaine
  - romaine lettuce

parmesan_cheese_grated:
  - Cheese, parmesan, grated
  - parmesan cheese grated
  - parmesan grated
  - grated parmesan
  - parmesan

croutons:
  - Croutons, plain
  - Croutons, seasoned
  - croutons plain
  - croutons
  - bread cubes

caesar_dressing:
  - Salad dressing, caesar
  - Salad dressing, caesar, regular
  - caesar dressing
  - dressing caesar
  - caesar salad dressing

tomatoes_raw:
  - Tomatoes, raw
  - tomatoes raw
  - tomato raw
  - fresh tomatoes

cucumber_with_peel_raw:
  - Cucumber, with peel, raw
  - cucumber with peel raw
  - cucumber raw
  - cucumbers raw

pizza:
  - pizza
  - cheese pizza
  - pizza slice

bagel:
  - bagel
  - bagels

meatball:
  - meatball
  - meatballs

dumpling:
  - dumpling
  - dumplings

chicken_salad:
  - chicken salad

caesar_salad:
  - caesar salad
  - romaine

cheese:
  - cheese
  - shredded cheese
